### ISSUE TITLE
Lost connection to MySQL

### ISSUE THREAD

**Issue by erjanmx** [erjanmx/salam-bot#19]
Обраывается связь

```
ERROR:root:(0, '') (SQL: SELECT * FROM `users` WHERE `users`.`id` = %s LIMIT 1 ([]))
Traceback (most recent call last):
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/pymysql/connections.py", line 855, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1071, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./app.py", line 24, in entry
    bot.run()
  File "./src/bot.py", line 34, in run
    getattr(self, self.events[self.event])()
  File "./src/bot.py", line 57, in event_new_message
    user = User.find_or_fail(self.request['sender_id'])
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 147, in find_or_fail
    result = self.find(id, columns)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 107, in find
    return self.first(columns)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 170, in first
    return self.take(1).get(columns).first()
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 198, in get
    models = self.get_models(columns)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 444, in get_models
    results = self.apply_scopes().get_query().get(columns).all()
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: (0, '') (SQL: SELECT * FROM `users` WHERE `users`.`id` = %s LIMIT 1 ([]))
ERROR:root:(0, '') (SQL: SELECT * FROM `users` WHERE `users`.`id` = %s LIMIT 1 ([]))
Traceback (most recent call last):
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/pymysql/connections.py", line 855, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1071, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./app.py", line 24, in entry
    bot.run()
  File "./src/bot.py", line 34, in run
    getattr(self, self.events[self.event])()
  File "./src/bot.py", line 57, in event_new_message
    user = User.find_or_fail(self.request['sender_id'])
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 147, in find_or_fail
    result = self.find(id, columns)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 107, in find
    return self.first(columns)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 170, in first
    return self.take(1).get(columns).first()
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 198, in get
    models = self.get_models(columns)
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/orm/builder.py", line 444, in get_models
    results = self.apply_scopes().get_query().get(columns).all()
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/home/salam_bot/venv/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: (0, '') (SQL: SELECT * FROM `users` WHERE `users`.`id` = %s LIMIT 1 ([]))
```

**Comment by erjanmx** [comment]
Похоже что orator не может восстановить соединение

**Comment by erjanmx** [comment]
Найдено решение

Дело было в библиотеке PyMysql
